--@type:menu
--node Reeme框架API手册
	--node request(请求)
		--node request.index request总述
	--node response(返回)
		--node response.index response总述
	--node ORM(数据关系映射)
		--node ORM.index ORM总述
		--node ORM.defmodel 定义模型
		--node ORM.modelquery 使用单模型查询
		--node ORM.result 操作结果集(R)
		--node ORM.modelcreate 创建记录(C)
		--node ORM.modelupdate 更新记录(U)
		--node ORM.modeldel 删除记录(D)